config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'events#index'

  get '/welcome' => 'application#welcome', as: :application_welcome

  get '/events/add' => 'events#add', as: :events_add
  post '/events/add' => 'events#add', as: :events_add_post
  get '/events/invite' => 'events#invite', as: :events_invite
  post '/events/invite' => 'events#invite', as: :events_invite_post
  get 'events/rsvp' => 'events#rsvp', as: :events_rsvp
  post 'events/rsvp' => 'events#rsvp', as: :events_rsvp_post
  get 'events/agenda' => 'events#agenda', as: :events_agenda
  get 'events/guest_list' => 'events#guest_list', as: :events_guest_list
  get '/events(/:event_time)' => 'events#index', as: :events_index

  get '/hosts/register' => 'hosts#register', as: :hosts_register
  post '/hosts/register' => 'hosts#register', as: :hosts_register_post
  get '/hosts/login' => 'hosts#login', as: :hosts_login
  post '/hosts/login' => 'hosts#login', as: :hosts_login_post
  get '/hosts/edit_profile' => 'hosts#edit_profile', as: :hosts_edit_profile
  post '/hosts/edit_profile' => 'hosts#edit_profile', as: :hosts_edit_profile_post
  get '/hosts/logout' => 'hosts#logout', as: :hosts_logout

  get '/users/register' => 'users#register', as: :users_register
  post '/users/register' => 'users#register', as: :users_register_post
  get '/users/login' => 'users#login', as: :users_login
  post '/users/login' => 'users#login', as: :users_login_post
  get '/users/edit_profile' => 'users#edit_profile', as: :users_edit_profile
  post '/users/edit_profile' => 'users#edit_profile', as: :users_edit_profile_post
  get '/users/logout' => 'users#logout', as: :users_logout
end

app/models/host.rb
class Host < ApplicationRecord

  has_many :events

  attr_accessor :registration_password, :registration_password_repeat

  validates :email_addr, :passwd, :business_name, presence: true
  validates :email_addr, uniqueness: true

  def evaluate_registration
    if registration_password != registration_password_repeat
      errors.add(:registration_password, "and confirmation password don't match")
    elsif registration_password.blank?
      errors.add(:registration_password, 'required')
    end
    
    self.passwd = Digest::SHA256.hexdigest registration_password
  end

end

app/controllers/hosts_controller.rb
class HostsController < ApplicationController

  skip_before_action :authorize, :only => [:register, :login]

  def register
    if request.post?
      @host = Host.new(host_params)
      @host.evaluate_registration
      if @host.valid? && @host.save
        session[:account_type] = 'host'
        session[:host_id] = @host.id
        redirect_to events_index_path
      else
        flash[:error] = @host.errors.full_messages.map { |v| v }.join('<br/>')
        redirect_to hosts_register_path
      end
    else
      @host = Host.new
    end
  end

  def login
    if request.post?
      host = Host.find_by(email_addr: params[:email_addr], passwd: Digest::SHA256.hexdigest(params[:passwd]))
      if !host.blank?
        session[:account_type] = 'host'
        session[:host_id] = host.id
        redirect_to events_index_path
      else
        redirect_to hosts_login_path
      end
    end
  end

  def logout
    session[:account_type] = nil
    session[:user_id] = nil
    session[:host_id] = nil
    redirect_to application_welcome_path
  end

  def edit_profile
    if request.post?
      if @current_host.update(host_params)
        flash[:success] = 'Profile Updated'
        redirect_to hosts_edit_profile_path
      else
        flash[:error] = @current_host.errors.full_messages.map { |v| v }.join('<br/>')
        redirect_to hosts_edit_profile_path
      end
    else
      @host = @current_host
    end
  end

  private

  def host_params
    params.require(:host).permit(:email_addr, :registration_password, :registration_password_repeat, :business_name)
  end

end

app/views/hosts/edit_profile.html.erb
<div class="hosts form">
    <%= form_for @host, url: hosts_edit_profile_path, method: :post do |f| %>
        <fieldset>
            <legend>Host Registration</legend>
            <%= f.label "email_addr", "Email Address *" %>
            <%= f.text_field "email_addr" %>
            <%= f.label "business_name", "Business Name *" %>
            <%= f.text_field "business_name" %>
        </fieldset>
        <div style="float:right;">
            <%= f.submit "Update" %>
        </div>
        <div style="clear:both;"></div>
    <% end %>
</div>

app/views/hosts/login.html.erb
<div class="loginForm">
    <h2>Host Log In</h2>
    <%= form_tag hosts_login_path, method: :post do %>
      <%= label_tag "email_addr", "Email Address" %>
      <%= text_field_tag "email_addr" %>
      <%= label_tag "passwd", "Password" %>
      <%= password_field_tag "passwd" %>
      <%= submit_tag "Login" %>
    <% end %>
</div>
<br/>
<div class="loginForm">
    <p>Don't have a socialite account?</p>
    <br/>
    <%= link_to "Register Now", hosts_register_path %>
    <br/>
    <%= link_to "Login as a user", users_login_path %>
</div>

app/views/hosts/register.html.erb
<div class="loginForm">
    <%= form_for @host, url: hosts_register_path, method: :post do |f| %>
        <fieldset>
            <legend>Host Registration</legend>
            <%= f.label "email_addr", "Email Address *" %>
            <%= f.text_field "email_addr" %>
            <%= f.label "registration_password", "Password *" %>
            <%= f.password_field "registration_password" %>
            <%= f.label "registration_password_repeat", "Repeat Password *" %>
            <%= f.password_field "registration_password_repeat" %>
            <%= f.label "business_name", "Business Name *" %>
            <%= f.text_field "business_name" %>
        </fieldset>
        <div style="float:right;">
            <%= f.submit "Register" %>
        </div>
        <div style="clear:both;"></div>
    <% end %>
</div>