config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'events#index'

  get '/welcome' => 'application#welcome', as: :application_welcome

  get '/events/add' => 'events#add', as: :events_add
  post '/events/add' => 'events#add', as: :events_add_post
  get '/events/invite' => 'events#invite', as: :events_invite
  post '/events/invite' => 'events#invite', as: :events_invite_post
  get 'events/rsvp' => 'events#rsvp', as: :events_rsvp
  post 'events/rsvp' => 'events#rsvp', as: :events_rsvp_post
  get 'events/agenda' => 'events#agenda', as: :events_agenda
  get 'events/guest_list' => 'events#guest_list', as: :events_guest_list
  get '/events(/:event_time)' => 'events#index', as: :events_index

  get '/hosts/register' => 'hosts#register', as: :hosts_register
  post '/hosts/register' => 'hosts#register', as: :hosts_register_post
  get '/hosts/login' => 'hosts#login', as: :hosts_login
  post '/hosts/login' => 'hosts#login', as: :hosts_login_post
  get '/hosts/edit_profile' => 'hosts#edit_profile', as: :hosts_edit_profile
  post '/hosts/edit_profile' => 'hosts#edit_profile', as: :hosts_edit_profile_post
  get '/hosts/logout' => 'hosts#logout', as: :hosts_logout

  get '/users/register' => 'users#register', as: :users_register
  post '/users/register' => 'users#register', as: :users_register_post
  get '/users/login' => 'users#login', as: :users_login
  post '/users/login' => 'users#login', as: :users_login_post
  get '/users/edit_profile' => 'users#edit_profile', as: :users_edit_profile
  post '/users/edit_profile' => 'users#edit_profile', as: :users_edit_profile_post
  get '/users/logout' => 'users#logout', as: :users_logout
end

app/models/event.rb
class Event < ApplicationRecord

  belongs_to :host
  has_many :invites
  has_many :users, through: :invites
  enum event_type: [:public, :invite], _prefix: true

  validates :event_name, :capacity, :event_start, :event_end, :rsvp_start, :rsvp_end, :event_type, :venue_addr1, :venue_city, :venue_state, :venue_zip, presence: true

  def self.get_upcoming_public_events
    self.where(event_type: :public).where('`event_start` >= ?', Time.now)
  end

  def self.get_past_public_events
    self.where(event_type: :public).where('`event_start` < ?', Time.now)
  end

  def self.get_events_for_user(user_id)
    self.left_joins(:invites).where('invites.user_id = ? OR events.event_type = ?', user_id, :public).distinct
  end

  def self.get_agenda_for_user(user_id)
    self.find_by_sql(["SELECT e.* FROM socialite_development.events AS e
        LEFT OUTER JOIN socialite_development.invites AS i
        ON i.event_id = e.id
        LEFT OUTER JOIN socialite_development.users as u
        ON u.id = i.user_id
        WHERE (i.user_id = ?)
        AND e.event_start >= NOW()", user_id])
  end

  def self.get_upcoming_events_by_host(host_id)
    self.where(host_id: host_id).where('`event_start` >= ?', Time.now)
  end

  def self.get_past_events_by_host(host_id)
    self.where(host_id: host_id).where('`event_start` < ?', Time.now)
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  before_action :only_host_action, only: [:add]

  def index
    @event_time = if params[:event_time].blank? || ['upcoming', 'past'].index(params[:event_time]).nil?
      'upcoming'
    else
      params[:event_time]
    end
    @events = if @account_type == 'host'
      if @event_time == 'upcoming'
        Event.get_upcoming_events_by_host(@current_host.id)
      else
        Event.get_past_events_by_host(@current_host.id)
      end
      else
      if @event_time == 'upcoming'
        Event.get_events_for_user(@current_user.id)
      else
        Event.get_past_public_events
      end
    end
  end

  def add
    if request.post?
      @event = Event.new(event_params.merge(host_id: @current_host.id))
      if @event.valid? && @event.save
        redirect_to events_index_path
      else
        flash[:error] = @event.errors.full_messages.map { |v| v }.join('<br/>')
        redirect_to events_add_path
      end
    else
      @event = Event.new
    end
  end

  def invite
    if request.post?
      @invite = Invite.new(event_id: params[:event_id], user_id: params[:user_id])
      @invite.save
      redirect_to events_invite_path(event_id: params[:event_id])
    else
      @event = Event.find_by(id: params[:event_id])
      @users = if params[:search]
                 User.search(params[:search])
               else
                 User.all
               end
    end
  end

  def rsvp
    if request.post?
      additional_guests = params[:invite][:additional_guests]
      if params[:rsvp] == 'false'
        additional_guests = 0
      end
      @event = Event.find_by(id: params[:event_id])
      @invite = Invite.find_by(event_id: params[:event_id], user_id: params[:user_id])
      if @invite
        if @event.event_type == 'public' && params[:rsvp] == 'false'
          @invite.destroy
        else
          @invite.update(rsvp: params[:rsvp], additional_guests: additional_guests)
        end
      else
        if params[:rsvp] == 'true'
          @invite = Invite.new(event_id: params[:event_id], user_id: params[:user_id], rsvp: params[:rsvp], additional_guests: additional_guests)
          @invite.save
        end
      end
      redirect_to events_index_path
    else
      @event = Event.find_by(id: params[:event_id])
      @invite = Invite.find_by(event_id: params[:event_id], user_id: @current_user.id)
      if !@invite
        @invite = Invite.new
      end
    end
  end

  def agenda
    @events = Event.get_agenda_for_user(@current_user.id)
  end

  def guest_list
    @guests = User.get_guest_list(params[:event_id])
    respond_to do |format|
      format.html
      format.csv { send_data @guests.to_csv }
    end
  end

  private

  def event_params
    params.require(:event).permit(:event_name, :description, :capacity, :event_start, :event_end, :rsvp_start, :rsvp_end, :event_type, :venue_addr1, :venue_addr2, :venue_city, :venue_state, :venue_zip)
  end

  def rsvp_params
    params.require(:invite).permit(:rsvp, :additional_guests)
  end

end

app/views/events/add.html.erb
<div class="events form">
    <%= form_for @event, url: events_add_path, method: :post do |f| %>
        <fieldset>
            <legend>Add Event</legend>
            <%= f.label "event_name", "Event Name *" %>
            <%= f.text_field "event_name" %>
            <%= f.label "description", "Description" %>
            <%= f.text_area "description" %>
            <%= f.label "capacity", "Capacity *" %>
            <%= f.text_field "capacity" %>
            <%= f.label "event_start", "Event Start *" %>
            <%= f.datetime_field "event_start" %>
            <%= f.label "event_end", "Event End *" %>
            <%= f.datetime_field "event_end" %>
            <%= f.label "rsvp_start", "RSVP Start *" %>
            <%= f.datetime_field "rsvp_start" %>
            <%= f.label "rsvp_end", "RSVP End *" %>
            <%= f.datetime_field "rsvp_end" %>
            <%= f.label "event_type", "Event Type *" %>
            <%= f.select "event_type", options_for_select(Event.event_types.inject({}){ |het, et| het.merge( et.first.capitalize => et.first )}), { style: 'width: 100%;' } %>
            <%= f.label "venue_addr1", "Venue Address 1 *" %>
            <%= f.text_field "venue_addr1" %>
            <%= f.label "venue_addr2", "Venue Address 2" %>
            <%= f.text_field "venue_addr2" %>
            <%= f.label "venue_city", "Venue City *" %>
            <%= f.text_field "venue_city" %>
            <%= f.label "venue_state", "Venue State *" %>
            <%= f.text_field "venue_state" %>
            <%= f.label "venue_zip", "Venue Zip *" %>
            <%= f.text_field "venue_zip" %>
        </fieldset>
        <div style="float:right;">
            <%= f.submit "Add" %>
        </div>
        <div style="clear:both;"></div>
    <% end %>
</div>

app/views/events/agenda.html.erb
<div class="events index">
  <h2>My Agenda</h2>
  <% if !@events.blank? %>
    <% @events.each do |event| %>
      <h3><%= event.event_name %></h3>
      <div class="event_listing">
        <div class="event_listing_left">
          <%= image_tag "default_event.jpg", width: "90" %>
        </div>
        <div class="event_listing_right">
          <p><span class="small_title">Location: </span><%= "#{event.venue_addr1}, #{event.venue_city}, #{event.venue_state} #{event.venue_zip}" %></p>
          <p><span class="small_title">Start Time: </span><%= event.event_start %></p>
          <p><span class="small_title">End Time: </span><%= event.event_end %></p>
          <p><span class="small_title">Details: </span><%= event.description %></p>
        </div>
        <div style="clear:both;"></div>
      </div>
    <% end %>
  <% else %>
      <h3>You have no upcoming events</h3>
  <% end %>
</div>

app/views/events/index.html.erb
<div class="events index">
    <% if @event_time == 'upcoming' %>
        <h2><%= @account_type == 'host' ? 'My Upcoming Events' : 'Upcoming Events' %></h2>
    <% else %>
        <h2><%= @account_type == 'host' ? 'My Past Events' : 'Past Events' %></h2>
    <% end %>
    <table>
        <tr>
            <% if @account_type == 'host' %>
                <td class="actions" width="60">
                    <%= link_to "Add Event", events_add_path %>
                </td>
            <% end %>
            <td class="actions">
                <%= link_to "Upcoming", events_index_path('upcoming') %>
                <%= link_to "Past", events_index_path('past') %>
            </td>
        </tr>
    </table>

    <% if !@events.blank? %>
        <% @events.each do |event| %>
            <h3><%= event.event_name %></h3>
            <div class="event_listing">
                <div class="event_listing_left">
                    <%= image_tag "default_event.jpg", width: "90" %>
                </div>
                <div class="event_listing_right">
                    <p><span class="small_title">Location: </span><%= "#{event.venue_addr1}, #{event.venue_city}, #{event.venue_state} #{event.venue_zip}" %></p>
                    <p><span class="small_title">Start Time: </span><%= event.event_start %></p>
                    <p><span class="small_title">End Time: </span><%= event.event_end %></p>
                    <p><span class="small_title">Details: </span><%= event.description %></p>
                    <p><span class="small_title">Guests: <%= event.invites.where(rsvp: true).count + event.invites.where(rsvp:true).sum(:additional_guests) %></span></p>
                    <% if @account_type == 'host' %>
                        <p><span class="small_title">Type: </span><%= event.event_type %></p>
                    <% end %>
                </div>

              <% if @event_time == 'upcoming' && @account_type == 'host' %>
                <div class="actions">
                  <ul>
                    <% if event.event_type == 'invite' %>
                      <li><%= link_to 'Invite Guests', events_invite_path(:event_id => event.id) %></li>
                    <% end %>
                    <li><%= link_to 'Download Guest List', events_guest_list_path(:event_id => event.id, :format => :csv) %></li>
                  </ul>
                </div>
              <% end %>
              <% if @account_type == 'user' %>
                <% if @event_time == 'upcoming' %>
                  <% if event.capacity - (event.invites.where(rsvp: true).count + event.invites.where(rsvp:true).sum(:additional_guests)) > 0 %>
                    <div class="actions">
                      <ul>
                        <li><%= link_to 'RSVP', events_rsvp_path(:event_id => event.id, :user_id => @current_user.id) %></li>
                      </ul>
                    </div>
                  <% else %>
                    <h3>Event Full</h3>
                  <% end %>
                <% end %>
              <% end %>
              <div style="clear:both;"></div>
            </div>
        <% end %>
    <% else %>
        <% if @event_time == 'upcoming' %>
            <h3>You have no upcoming events in this section</h3>
        <% else %>
            <h3>You have no past events in this section</h3>
        <% end %>
    <% end %>
</div>

app/views/events/invite.html.erb
<div class="events index">
  <%= form_tag(events_invite_path, :method => "get") do %>
    <h3>Invite to <%= @event.event_name %></h3>
    <%= hidden_field_tag :event_id, @event.id %>
    <%= text_field_tag :search, "Search for Users"%>
    <%= submit_tag "Search", :name => nil %>
  <% end %>
    <table>
      <thead>
        <tr>
          <td>
            First Name
          </td>
          <td>
            Last Name
          </td>
          <td>
            Email
          </td>
          <td>
            Invite
          </td>
        </tr>
      </thead>
      <% @users.each do |user| %>
        <tbody>
          <tr>
            <td>
              <%= user.first_name %>
            </td>
            <td>
              <%= user.last_name %>
            </td>
            <td>
              <%= user.email_addr %>
            </td>
            <td>
              <%= button_to 'Invite', {:controller => "events", :action => "invite", :event_id => params[:event_id], :user_id => user.id}, :method=>:post %>
            </td>
          </tr>
        </tbody>
      <% end %>
    </table>
</div>

app/views/events/rsvp.html.erb
<div class="events index">
  <h3>RSVP to <%= @event.event_name%></h3>
  <%= form_for @invite, url: events_rsvp_path, method: :post do |f| %>
    <div>
      <%= hidden_field_tag "event_id", params[:event_id] %>
      <%= hidden_field_tag "user_id", params[:user_id] %>
      <%= select_tag "rsvp", options_for_select([['Yes', true], ['No', false]],:selected => @invite.rsvp)  %>
      <%= f.label "additional_guests", "Additional Guests" %>
      <%= f.text_field "additional_guests" %>
      <%= f.submit "Update" %>
    </div>
  <% end %>
</div>